version: '3.8'

services:
  notebooks:
    container_name: notebooks
    build: .
    ports:
      - 8888:8888
      - 40000:40000
    volumes:
      - ./notebooks:/notebooks
      - ./tables:/tables
      - ./images:/images
